# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180812_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enroll_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
